name: actions file for frontend code
on:
  push:
    branches:
      - "master"
jobs:
  initializing-and-testing-code:
    runs-on: ubuntu-latest
    steps:
      - name: checking-out-repo
        uses: actions/checkout@v2
      
      - name: setting up node
        uses: actions/setup-node@v2
        with:
          node-version: "17"

  deploying_the_code:
    needs: initializing-and-testing-code
    runs-on: ubuntu-latest
    steps:
      - name: running the command to deploy 
        uses: appleboy/ssh-action@master
        with:
          host: ssh -i "legacy-lms-uat.pem" ubuntu@ec2-3-111-35-62.ap-south-1.compute.amazonaws.com
          username: ubuntu
          key: ${{secrets.SSH_PEM_KEY}}
          port: 22
          script: |
            cd /home/ubuntu/Artmate_frontend/arthmate_frontend
            git pull origin master
            npm i
            pm2 delete all
            pm2 --name analyticsfox start npm -- start
