name: Deployment

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2

      - run: npm i
      - run: pm2 delete all
      - run: pm2 --name analyticsfox start npm -- start

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /home/ubuntu/Artmate_frontend/arthmate_frontend
          remote_host: ssh -i "legacy-lms-uat.pem" ubuntu@ec2-3-111-35-62.ap-south-1.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PEM_KEY }}"
